# permissions for end users to edit databacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databack-editor-role
rules:
- apiGroups:
  - operator.kubeimooc.com
  resources:
  - databacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kubeimooc.com
  resources:
  - databacks/status
  verbs:
  - get
